### ISSUE TITLE
FCTCUSTOMERORDER.csv: Columns have no names

### ISSUE THREAD

**Issue by droettningu** [saphanaacademy/PAL#1]

**Comment by saphanaacademy** [comment]
This is normal. The csv files are imported via the script referenced in the readme: https://github.com/saphanaacademy/PAL/blob/master/Source%20Data/PAL/readme.txt.
For HANA 2 releases you may find it easier to import the schema from the provided zip - process is covered in the getting started video for the corresponding HANA release eg: HANA SPS 02.
