### ISSUE TITLE
Not compatible with HANA2.0SP02

### ISSUE THREAD

**Issue by luto65** [saphanaacademy/PAL#2]
Unfortunately this code is not compatible with HANA2.0SP2

**Comment by ebarlason** [comment]
Hi!

I would like to do analysis using Pearson’s correlation coefficient matrix and I am currently on HANA 2.0 SPS02. Do you know where can I find the compatible code for sps02??

**Comment by saphanaacademy** [comment]
Hi,
The HANA Academy provide code examples here but it's not practical to cover every single algorithm in every single HANA release. You can get the idea of SPS02 syntax by looking at another algorithm in this repo that has the SPS02 suffix and watching the corresponding video tutorials. Or you can use the PAL reference guide for here: [https://help.sap.com/viewer/2cfbc5cf2bc14f028cfbe2a2bba60a50/2.0.02/en-US/e872de9ce09042c2b8e79a4026e9b4d0.html](url)
Thanks,
Philip
