### ISSUE TITLE
Deprecated SYSTEM.AFL_WRAPPER_GENERATOR in PAL 47 Statistics - Multivariate.sql

### ISSUE THREAD

**Issue by sarahESL** [saphanaacademy/PAL#3]
I think ```PAL 47 Statistics - Multivariate.sql``` is outdated (does not work for me) as ```SYSTEM.AFL_WRAPPER_GENERATOR``` is deprecated and the script should be update to use ```SYS.AFLLANG_WRAPPER_PROCEDURE_CREATE``` instead => https://help.sap.com/viewer/2cfbc5cf2bc14f028cfbe2a2bba60a50/2.0.01/en-US/e872de9ce09042c2b8e79a4026e9b4d0.html?q=multivariate%20statistics

**Comment by saphanaacademy** [comment]
Hi Sarah,
Indeed this particular example refers to syntax for a prior version of HANA - however some customers are still using this version so the code is still relevant. 
Whilst we provide code examples here it's not possible for us to cover every single algorithm for every single HANA release. You can get the idea of how to use more recent syntax by looking at another algorithm example in this repo which has the HANA SPSnn suffix you're on and also by watching the corresponding video tutorials. Or you can use the PAL reference guide as you mentioned.
Thanks,
Philip
